### ISSUE TITLE
Performance: Part.FindModulesImplementing does not actually populate the cache

### ISSUE THREAD

**Issue by JonnyOThan** [KSPModdingLibs/KSPCommunityFixes#102]
Like FindModuleImplementing; this function checks a cache for its result.  However it does not ever put data *into* the cache so it does the full search every time it's called.

Further, it always allocates a new list; returning the one from the cache might be better (but also slightly dangerous if any of the callers are relying on the fact that it's a new list and modify it).

**Comment by gotmachine** [comment]
TBH, not worth a fix  : 
1. The method allocate a new list on each call. Changing that behavior is more than slightly dangerous, it **will** break stuff. I can see at least two cases in stock code, probably many more in mods.
2. Since it allocate a new list, this method should never be used in any kind of hot path, but only in setup/init code, therefore is pointless and even counterproductive to bloat it with a caching mechanism.

I guess we could remove the `if (cachedModuleLists.ContainsKey(typeFromHandle))` block entirely to avoid the (tiny) perf overhead.

**Comment by JonnyOThan** [comment]
I came across this because RPM is using this function every frame; there are quite likely other mods that do similar things.

Where are the locations that modify the returned list?  We could patch those to make a copy.

I don't think removing the branch is worthwhile; the iteration over all modules is the expensive bit.

**Comment by gotmachine** [comment]
> I came across this because RPM is using this function every frame; there are quite likely other mods that do similar things.

Well, then it's those mods problem, they shouldn't be using that method in this case and if they need some caching mechanisms they should implement it themselves. The premise of KSPCF is to not alter the stock API and to put compatibility first. 

> We could patch those to make a copy.

We can patch stock but we can't patch the mods that rely on the new list instance behavior.

**Comment by JonnyOThan** [comment]
Yeah, I'd agree that it's probably too dangerous to return the cached list.  Still, I think it's worthwhile to fix the caching behavior.  You could even keep a static empty list for the null result (which is probably going to occur a lot of the time).

I see a few places in the stock code that call this every frame, like ModuleAsteroidDrill.PrepareRecipe, ModuleCoreHeat.CheckCoreShutdown, etc.

**Comment by NathanKell** [comment]
hi! Popping back online for a bit (sorry folks) -- I too think it's
valuable to do the caching and then just copy to a new list on each call.
I'm of two minds as to whether it's correct to return a static empty list
or to *always* return a new list and avoid any bugs wrt that.

**Comment by gotmachine** [comment]
What about : 
- We fix the caching, but keep returning a new list in the stock method
- We provide an alternate performance oriented method that return an IEnumerable struct for efficiently iterating/updating the cache without allocations
- We patch the relevant stock locations to use that alternate methods
- Mods are free to copypaste the method or to call the KSPCF one (directly or through reflection)

**Comment by gotmachine** [comment]
Just gave a real look at this.

Patching this method is a mess. Patching generic methods can already be unreliable, but in this case we need access to the generic argument and there is no sane way to get it from a prefix.

Maybe something can be hacked together with a transpiler and a lot of coffee, but I don't have the courage to engage such hostilities.

Again optimizing this method will have almost zero benefit in stock, and in any case the method signature isn't appropriate for a hot path use case.

**Comment by gotmachine** [comment]
So, did a few tests.

First, something to note is that using the cache has some overhead. Obviously it is vastly slower for a one-time call, and even for repeated calls, it only starts to be faster than a `while (moduleCount-- > 0)` if the part has more than ~6-7 modules. 

So for some practical use cases like a "foreach part, foreach module", at least in stock the cached version is overall slightly slower (microbenchmarked on a few stock crafts). In a heavily modded game where the average module count per part is much higher this might start to yield some benefits.

All in all, this is really a micro-optimization that is only significant for very hot paths. In terms of absolute performance gains, it's in the same realm as using a while loop instead of foreach. 

Also note that the perf gains over a direct module iteration just vanish if you want to make the helper method idiot proof to prevent the consumer from accidentally adding or removing modules from the cached list (which is definitely needed if the method is to be consumed by random mods). The fastest way I found is to return a custom struct iterator, and in this case the module count threshold at which the cache is faster is around 20...

So, given that : 
1. The stock method is barely used in stock (it is only called every update in a single case, in `ModuleAsteroidDrill.PrepareRecipe`)
2. The stock method is a mess to patch due to generics support issues in Harmony (I'm not even sure it's doable)
3. Even if it was using the cache, we can't safely patch it to directly return the cached list. The main perf issue with that stock method is that it is instantiating a new list on every call, not that it doesn't use the cache.
4. Doing the caching is only beneficial in some limited "hot path" scenarios (and actually slower in some other use cases)
5. Using the cache for those scenarios is relatively trivial to implement from a mod.

I will close the issue.

For reference, if someone needs it for a mod, here is the method that return the cached list (requires either to publicize the `cachedModuleLists` field or to create a getter delegate for it) : 

```cs
public static class FindModuleExtensions
{
    public static List<PartModule> GetModulesImplementingCache <T>(this Part part) where T : PartModule
    {
        if (part.modules == null)
            return new List<PartModule>(0);

        Type moduleType = typeof(T);
        if (!part.cachedModuleLists.TryGetValue(moduleType, out List<PartModule> moduleList))
        {
            moduleList = new List<PartModule>();
            part.cachedModuleLists[moduleType] = moduleList;

            int mCount = part.modules.Count;
            while (mCount-- > 0)
                if (part.modules[mCount] is T)
                    moduleList.Add(part.modules[mCount]);
        }

        return moduleList;
    }
}
```
Usage :
```cs
List<PartModule> list = part.GetModulesImplementingCache<SomeModuleType>();
int idx = list.Count;
while (idx-- > 0)
    DoWork((SomeModuleType)list[idx]);
```

And just for fun, the custom iterator version : 
```cs
public struct ModuleIterator<T> : IEnumerable<T>, IEnumerable, IEnumerator<T>, IEnumerator, IDisposable where T : PartModule
{
    private List<PartModule> moduleList;
    private int idx;
    private int count;
    private T current;

    public ModuleIterator(Part part) : this()
    {
        if (part.modules == null)
            return;

        Type moduleType = typeof(T);
        if (!part.cachedModuleLists.TryGetValue(moduleType, out moduleList))
        {
            moduleList = new List<PartModule>();
            part.cachedModuleLists[moduleType] = moduleList;

            int mCount = part.modules.Count;
            while (mCount-- > 0)
                if (part.modules[mCount] is T)
                    moduleList.Add(part.modules[mCount]);
        }

        count = moduleList.Count;
    }

    T IEnumerator<T>.Current => current;
    object IEnumerator.Current => current;
    public IEnumerator<T> GetEnumerator() => this;
    IEnumerator IEnumerable.GetEnumerator() => this;

    private bool MoveNext()
    {
        if (count == 0 || count >= idx)
        {
            return false;
        }

        current = (T)moduleList[idx];
        idx++;
        return true;

    }

    bool IEnumerator.MoveNext() => MoveNext();
    void IEnumerator.Reset() => throw new NotSupportedException();
    void IDisposable.Dispose() {}
}

public static class FindModuleExtensions
{
    public static ModuleIterator<T> GetModulesImplementingIterator<T>(this Part part) where T : PartModule
    {
        return new ModuleIterator<T>(part);
    }
}
```
Usage : 
```cs
foreach (SomeModuleType module in part.GetModulesImplementingIterator<SomeModuleType>())
  DoWork(module);
```
