### ISSUE TITLE
Ksp stops loading at about halfway with update 1.24.1

### ISSUE THREAD

**Issue by Jaspsteen** [KSPModdingLibs/KSPCommunityFixes#113]
After updating, Ksp stops loading halfway. The loading bar doesn't display any active processes and the game doesn't progress.

**Comment by gotmachine** [comment]
Please upload your KSP.log file, I can't do anything without more information.

**Comment by Jaspsteen** [comment]
This is my log, on a clean install with KSPCF 1.24.2:
[https://www.dropbox.com/s/zuh3wbj8251zy0m/ksp.log?dl=0]

**Comment by gotmachine** [comment]
Mmmh, can't test right now, but I guess some KSPCF patch isn't working with KSP 1.12.0, unfortunately your log is likely truncated
Any reason you're not upgrading to a more recent KSP version ? 1.12.1, 12.2 and 1.12.3 have a several important bug fixes.

Also, did you get that issue previously (with KSPCF 1.23.x) ?

**Comment by Jaspsteen** [comment]
No, the 1.23 versions work just fine, I'll try updating, thanks.

**Comment by gotmachine** [comment]
Yeah, this is caused by some minor difference in the stock PartLoader implementation in KSP 1.12.0/1.12.1/1.12.2.
The FastLoader patch was written against KSP 1.12.3, I wrongly assumed that it would work in previous patch versions.
KSPCF 1.24.5 now require KSP 1.12.3+ for the FastLoader patch to be active.
