### ISSUE TITLE
KSP Orbit class needs to be more careful about meanMotion vs. GetMeanMotion() calls

### ISSUE THREAD

**Issue by lamont-granquist** [KSPModdingLibs/KSPCommunityFixes#141]
Kopernicus doesn't use the simple formula in GetMeanMotion(), but instead updates the period and meanMotion for the combined mass of the bodies:

```
// this is unlike stock KSP, where only the reference body's mass is used.
body.orbit.period = 2 * Math.PI * Math.Sqrt(Math.Pow(body.orbit.semiMajorAxis, 2) / 6.67408e-11 * body.orbit.semiMajorAxis / (body.referenceBody.Mass + body.Mass));
body.orbit.meanMotion =  2 * Math.PI / body.orbit.period; // in theory this should work but I haven't tested it
```

This is an "interesting" choice which means that you can't just grab the gravParameter of the central body and assume that is mu for Keplerian propagation, but more importantly this way of using the Orbit class implicitly assumes that GetMeanMotion() is only called on initialization.  It will always be incorrect to be called anytime after Kopernicus is done updating the period and meanMotion fields.

And this can be seen just by a simple test using RSS:

```
moon.orbit.meanMotion = 2.66626696009041E-06
moon.orbit.GetMeanMotion(moon.orbit.semiMajorAxis) = 2.65001910331826E-06
```

At a minimum there are a couple uses of GetMeanMotion() in the Orbit class which should use the field instead in `getUTAtMeanAnomaly(double M, double UT)`, `getMeanAnomalyAtUT(double UT)`, `GetNextPeriapsisTime(double UT)`, and `NextCloseApproachTime(Orbit p, Orbit s, double UT)`.

The calls in Init(), and UpdateFromFixedVectors() are presumably okay because the first is initialization and the second is an API nobody should touch (famous last words?) on a celestial orbit that Kopernicus has messed around with.

The fix is simple and the calls to GetMeanMotion() in those methods should just be replaced by accessing the field.

I don't see any references to GetMeanMotion() outside of the Orbit class.

Unfortunately, I'm unaware of any actual bugs caused by this, I was just beating my face against the fact that the my attempt to calculate Keplerian propagation of the Moon's orbit outside of the KSP Orbit class was incorrect and now I can reverse the period/meanMotion variables to calculate an effective gravParameter and that solves my problem.

These APIs very clearly HAVE to be buggy though.

**Comment by lamont-granquist** [comment]
This will only affect Celestials and not ships, and only affects Kopernicus-using mods, and is going to be most apparent with the Moon in RSS.

It would almost be good to have something that would update GetMeanMotion() to check if it was being called on an orbit for a celestial and would logspam a warning that the use of that API was inconsistent with Kopernicus.  That's just a showerthought I've got though.

**Comment by lamont-granquist** [comment]
(Alternatively that bit of cleverness could be ripped out of Kopernicus--the difference it makes in the Moon's orbital propagation is clearly pretty small and the right solution is probably spelled Principia).

**Comment by gotmachine** [comment]
> Alternatively that bit of cleverness could be ripped out of Kopernicus--the difference it makes in the Moon's orbital propagation is clearly pretty small and the right solution is probably spelled Principia

This seems to me to be the only sane thing to do. Kopernicus trying to alter the KSP orbital mechanics model is questionable in the first place, to change it *only for bodies* is even more questionable, and I don't think it's actually possible to have the KSP API surface behave consistently in such a scenario. 

Patching `Orbit.Init()` and `Orbit.UpdateFromFixedVectors()` to use the field would affect everything, not only bodies, it's not possible to reliably detect where the call is originating from.

Overall, this feels like another case of Kopernicus trying to do questionable stuff that has nothing to do with its main purpose in a questionable way that mainly result in new bugs...

In any case, this isn't a stock issue, but a Kopernicus issue and should be addressed by Kopernicus, there is zero reason to touch how stock is behaving from KSPCF, and Kopernicus can use the same tools as KSPCF to do whatever it wants.

Bluntly removing that feature from Kopernicus might result in some weirdness for ongoing games in systems using the `finalizeOrbit` thing, so that's probably not a viable option. At the very least, I think the shortcomings should be warned against in the docs and gated behind an additional optional config switch, assuming `finalizeOrbit` has other purposes. Not sure what the other stuff here is about : https://github.com/Kopernicus/Kopernicus/blob/a26d067681b7c90140d15790f1acd0a93d6df7b3/src/Kopernicus/Configuration/OrbitLoader.cs#L372-L432, I don't understand why hill sphere / SOI are recomputed here...

I feel like this hack is originating from wanting to have closer to RL periods for RSS bodies before Principia was a thing. I would suggest simply removing all `finalizeOrbit = true` in RSS, possibly resulting in some side effects for ongoing games, and learn to live with the fact that KSP orbital mechanics are a quite simplified model...
