### ISSUE TITLE
fix processing an experiment in the lab and sending to KSC in the same time

### ISSUE THREAD

**Issue by yalov** [KSPModdingLibs/KSPCommunityFixes#15]
Now it's possible to start process experiment in the lab, and sent to KSC at the same time.
Also it is (probably) possible to processing same experiment in different labs and having unlimited science points

fix: 
start processing an experiment in the lab makes the experiment be obtained - so no more science from lab or recovering in the KSC.

**Comment by gotmachine** [comment]
As far as I can tell, this has always been the case. 
The stock lab is more or less designed to allow infinite science anyway.

TBH, I don't see that as a thing worth fixing (especially since that would be quite some work). 
It's not really a bug, just another terrible KSP feature. If you find it cheaty, just don't do it.
