### ISSUE TITLE
Bounds calculation should consider the default or active variant given by a part config for parts with varying sizes

### ISSUE THREAD

**Issue by JadeOfMaar** [KSPModdingLibs/KSPCommunityFixes#208]
Concerning a conversation with @JonnyOThan and AlphaMensae on the subject of parts with mesh switch configs and various sizes it was highlighted that KSP doesn't adjust the bounds of a part depending on its variant and the related change of size. KSP always assumes the maximum size and this is reflected in the Engineer Report in the ship editors. Parts that animate do not suffer this issue so maybe a cue can be taken from how those are handled.

I figured and confirmed that this issue means that parts with variants will not agree with the cargo shielding module if any variant exceeds a given cargo bay's shielding radius. In this test craft a ruler set to its shortest size but still produces drag. Its greatest size is also shown for reference.

To reproduce this issue, place a part with varying sizes in a cargo bay, set it to its smallest that can fit (this part must have a size that's clearly longer than the cargo bay is), launch it, turn on aero info in PAWs, get the craft moving and watch the drag value in the part's PAW.

Required mods:
- Measurizer
- B9 Part Switch

[Craft file](https://github.com/JadeOfMaar/sandbox/blob/f7e173e679aa20d74d2255b31bddd55ae945de2d/Troubleshoot/Bounds%20Carrier%20Test.craft)

![moving in flight, non-zero drag](https://i.imgur.com/5NPB0uP.png)
![showing ruler max length in SPH](https://i.imgur.com/sO7UCva.png)

**Comment by gotmachine** [comment]
Gave a quick look at this.

Part bounds used in the engineer report and for cargo bay occlusion are obtained by a call to `PartGeometryUtil.GetPartRendererBounds()`, which indeed doesn't ignore disabled renderers. It does however handle the exclusion of specific renderers by populating the `Part.partRendererBoundsIgnore` list with GameObject names. It also has a specific handling for the stock variant switcher. Note that this method is also used for a few flight scene code paths, notably the `Vessel.size` field update.

Ideally, non stock mesh switchers could be populating `Part.partRendererBoundsIgnore` to handle that issue, but maintaining that list when multiple sources are involved could be a bit messy, and realistically this isn't going to be implemented/fixed in every mesh switcher anytime soon.

The KSPCF solution would be to re-implement `PartGeometryUtil.GetPartRendererBounds()` (re-implementing the whole thing, we shouldn't touch the utility methods it is calling) so it ignore disabled renderers by default.

Given that this is used in many code paths exposing the results in various public ways, it could potentially have some unwanted side effects, but in this specific case I feel this is relatively safe to do, and would definitely fix many issues where non-stock switchers are causing incorrect bounds to be used.

**Comment by gotmachine** [comment]
So... actually, after thinking about it, it might be possible to directly patch `PartGeometryUtil.GetPartRendererBounds()` to solve the issue, by traversing the model hierarchy and checking if any gameobject is disabled (checking `activeSelf`), excluding it and its childs. Since prefab are disabled by disabling their top-level GameObject, this shouldn't affect them.

**Comment by gotmachine** [comment]
Patch seems to be working, very little testing done.

**Comment by gotmachine** [comment]
Released in 1.35.0
