### ISSUE TITLE
I can't enable RCS,control gimbal and throttle with KSPCF 1.36

### ISSUE THREAD

**Issue by Urizz** [KSPModdingLibs/KSPCommunityFixes#274]
**Describe your problem with KSPCF :**

**KSP version :**1.12.9
![ma](https://github.com/user-attachments/assets/85373e27-e001-465c-9bd5-347e3cf50e77)
![image](https://github.com/user-attachments/assets/e91a35f3-82a1-4a66-ad09-037d0d9c1409)

**Link to your `KSP.log` file :**
https://drive.google.com/file/d/1q2YrFKqhuT4AFx_W5KcjKXbnIiBNnG9n/view?usp=sharing LOG

**Comment by gotmachine** [comment]
Thanks for the report, and sorry for the inconvenience.
This caused by an [incompatibility with Universal Storage 2](https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/273), and is fixed [in KSPCF release 1.36.1](https://github.com/KSPModdingLibs/KSPCommunityFixes/releases/tag/1.36.1), things should be fine after updating.
