### ISSUE TITLE
Comet part mass not decreasing while mining

### ISSUE THREAD

**Issue by xiej2520** [KSPModdingLibs/KSPCommunityFixes#66]
A bug that is annoying when trying to move comets, but doesn't affect most players.

This bug can be reproduced by:
* attaching a mining rig to a comet and using a drain valve to get rid of the ore.

The mass and resources of the comet will decrease in the PAW for the comet, but the actual mass of the comet part, and the vessel, will not decrease. This can be verified by looking at the (i) info tab in map view for the mass of the vessel.

The bug occurs in both stock KSP 1.12.1, and KSP 1.12.1 with KSPCommunityFixes installed and the [Asteroid/Comet Mass revert bug](https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/51) fix enabled. It appears to only affect comets and not asteroids, making comets harder to move.

**Comment by gotmachine** [comment]
There is a bug matching exactly what youdescribe that was fixed in KSP 1.12.2 for asteroids, but wasn't implemented for comets (whose implementation is almost a 1:1 copypaste of asteroids).

But since you mention KSP 1.12.1, I would expect that bug to happen for both asteroids and comets. When you tested with asteroids, was it also in a 1.12.1 install ?

I will add a patch to port the asteroid bugfix to comets on 1.12.2 and 1.12.3, but I won't touch earlier versions.
While KSPCF supports KSP 1.8.0 to 1.12.3, I usually don't add patches for stock bugs that are fixed in the most recent versions.

**Comment by xiej2520** [comment]
Apparently I misread the version number I had on CKAN, I went back and doubled checked, the bug is for comets in 1.12.3, not 1.12.1. I presume that asteroids have the bug in 1.12.1. Thanks for looking into it, sorry about the mix-up!
