### ISSUE TITLE
Terrain disappearing when the camera is close to the ground

### ISSUE THREAD

**Issue by tony48** [KSPModdingLibs/KSPCommunityFixes#87]
Video of the bug : https://youtu.be/xfpvmWvLrzM
Video 2 : https://youtu.be/TGtglECDghA The bug doesn't seem to occur when switching to a craft at a higher altitude
This occurs in KSRSS when a vessel is landed in some parts (the lowest? see video 2) of the Valles Marineris canyon. When the camera approaches the ground, the terrain completely disappears.
KSP version : 1.12.3
Mods installed : 
Harmony 2.2.1
Kopernicus 1.12.1-139
KSRSS reborn branch on gitlab. To install it, download the repo https://gitlab.com/ksrss/KSRSS and copy the KSRSS folder to the KSP GameData.
ModularFlightIntegrator 1.2.10
ModuleManager 4.2.2
(VesselMover 1.12 for testing purposes, I've tested without it and the bug still occurs)
Save file : [save.zip](https://github.com/KSPModdingLibs/KSPCommunityFixes/files/9415721/save.zip)
To test, go into the tracking station, select the Buggy 1 craft and fly it. If for some reason the craft is destroyed, teleport a new craft to Mars to these coordinates using the set position in the alt F12 menu : -13.9 latitude, -59.2 longitude.

**Comment by GarwelGarwel** [comment]
I'm having this issue with JNSQ as well (e.g. Eve becomes dark even when you are outside its SOI).

**Comment by gotmachine** [comment]
Unless someone manage to reproduce this in stock, I'm gonna redirect that issue toward Kopernicus and our good frog @R-T-B

Even if the root cause is in some stock code (which is far from guaranteed, that could also be an issue in how Koperncius handle things), R-T-B and I are agreeing that fixes related to making modded planetary systems work should belong in Koperncius and not in KSPCF.

**Comment by R-T-B** [comment]
Just updating to let you know I agree and will look into this.
